### ISSUE TITLE
Where are CustomObjectDetection CustomVideoObjectDetection these files located??

### ISSUE THREAD

**Issue by YashKK2198** [OlafenwaMoses/FireNET#2]
Line number one is following:
from imageai.Detection.Custom import CustomObjectDetection, CustomVideoObjectDetection

But when I try to find the CustomObjectDetection and CustomVideoObjectDetection files in Custom folder which is inside the Detection folder, I am unable to locate them and my code is not able to import the same.

Please help me with this issue.

**Comment by OlafenwaMoses** [comment]
You have to install **ImageAI** to run the project. Follow the full instructions detailed in the **README**

**Comment by YashKK2198** [comment]
Yes I did install ImageAI. But the code is unable to find the location of : 
**_Custom import CustomObjectDetection, CustomVideoObjectDetection_**
above two files which are imported in the very first line of the code.

The above two files are expected to be in:
_**imageai  -----> Detection -----> Custom**_   folder. But Custom folder does not contain the above two files

**Comment by YashKK2198** [comment]
Yes it worked. I just needed to call a function. Thank you !
